<?php

namespace Shop\MenuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AutoMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoMenuRepository extends EntityRepository {

        public function findByIdOrderedByName($id) {
                                       
        $query = $this->createQueryBuilder('a')
            ->where('a.modelMenuId = :id')
            ->setParameter('id', $id)
            ->orderBy('a.name', 'ASC')
            ->getQuery();
        return $query->getResult();
        
    }

}
