<?php

namespace Shop\MenuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModelMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelMenuRepository extends EntityRepository
{
    
    public function findAllOrderedByName() {
                                       
        $query = $this->createQueryBuilder('m')
            //->where('p.price > :price')
            //->setParameter('price', '19.99')
            ->orderBy('m.name', 'ASC')
            ->getQuery();
        return $query->getResult();
        
        /*         
        $repository = $this->getEntityManager()->getRepository('ShopMenuBundle:ModelMenu');
        $query = $repository->createQueryBuilder('m')
                ->orderBy('m.name', 'ASC')
                ->getQuery();
        return $query->getResult();
        
        
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT m FROM ShopMenuBundle:ModelMenu m ORDER BY m.name ASC'
                        )
                        ->getResult();
        
        */
    }
    
}
