<?php

namespace Shop\MenuBundle\Repository;

/**
 * OneRubricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneRubricRepository extends \Doctrine\ORM\EntityRepository
{
}
