<?php

namespace Shop\MenuBundle\Repository;

/**
 * ThreeRubricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreeRubricRepository extends \Doctrine\ORM\EntityRepository
{
}
