<?php

namespace Shop\MenuBundle\Repository;

/**
 * TwoRubricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwoRubricRepository extends \Doctrine\ORM\EntityRepository
{
}
