imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ShopMenuBundle/Resources/config/services.yml" }
    - { resource: "@SecurityUserBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    img_directory: '%kernel.project_dir%/web/img/upload'

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig','@AdminBundle/Resources/views/fields.html.twig']
    
    
# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        options:
                1002: "SET NAMES 'UTF8' COLLATE 'utf8_unicode_ci'" 
        mapping_types:
            enum: string
        types:
            money: Tbbc\MoneyBundle\Type\MoneyType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       mail.autostopdrg.com.ua
    username:   _mainaccount@autostopdrg.com.ua
    password:   iYuU89kHsd
    
    #transport: '%mailer_transport%'
    #host: '%mailer_host%'
    #username: '%mailer_user%'
    #password: '%mailer_password%'
    #port: 465
    #spool: { type: memory }

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:                                 
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:                                        
        pagination: '@AdminBundle/Resources/views/twitter_bootstrap_v4_pagination.html.twig'     # sliding pagination controls template                                    
        sortable:  "@AdminBundle/Resources/views/sortable_link.html.twig" #sort link template '@KnpPaginator/Pagination/sortable_link.html.twig'                               
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template

tbbc_money:
    currencies: ["UAH", "USD", "EUR", "PLN"]
    reference_currency: "UAH"
    decimals: 2
    storage: doctrine
    #ratio_provider: tbbc_money.ratio_provider.yahoo_finance
    ratio_provider: tbbc_money.ratio_provider.google

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr

    mappings:
        product_image:
            uri_prefix: "/img/upload"
            upload_destination: '%kernel.root_dir%/../web/img/upload'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../web"
                cache_prefix: "media/cache"

    filter_sets:
        cache: ~

        items_img_small:
            quality: 100
            filters:
                thumbnail: { size: [88, 50], mode: outbound }

        # the name of the "filter set"
        my_thumb:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:
                thumbnail: { size: [500, 500], mode: outbound }
                background: { size: [504, 504], position: center, color: '#00ff00' }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        jsqueeze: ~
        cssrewrite: ~
    assets:
        site_web:
            inputs:
                #- %kernel.root_dir%/../web/css/ben.css
                - "%kernel.root_dir%/../web/css/jquery-ui.css"
        site_web_js:
            inputs:
                - "%kernel.root_dir%/../web/js/jquery-ui.js"
        jquery:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js"
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap-theme.css"
            filters: [ cssrewrite ]
        bootstrap_glyphicons_ttf:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf"
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.eot"
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.svg"
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff"
            output: "fonts/glyphicons-halflings-regular.woff"