# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_denied_url: security_user_login
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Security\UserBundle\Entity\User: 
            algorithm: bcrypt
            cost: 5
            
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:        
        chain_provider:
            chain:
                providers: [ben_db_provider_user]
        ben_db_provider_user:
            entity:
                class: SecurityUserBundle:User
        
        #our_db_provider:
            #entity:
                #class: SecurityUserBundle:User
                #property: username
                # if you're using multiple entity managers
                # manager_name: customer
        #in_memory:
            #memory: ~

    role_hierarchy:
        ROLE_TEAM:        ROLE_USER
        ROLE_OPERATOR:    ROLE_USER
        ROLE_ADMIN:       [ROLE_TEAM,ROLE_OPERATOR]
        ROLE_ROOT:        [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #admin:
            #pattern: ^/(users)/
            #http_basic: ~
            #provider: ben_db_provider_user
           
            
        main:
            anonymous: ~
            form_login:
                login_path: security_user_login
                check_path: security_user_login_check
                default_target_path: shop_menu_homepage
                always_use_default_target_path: true
            logout:
                path: security_user_logout
                invalidate_session: true
                target: security_user_login            
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
