<?php

namespace AdminBundle\Repository;

/**
 * EmaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmaleRepository extends \Doctrine\ORM\EntityRepository
{
}
