<?php

namespace AdminBundle\Repository;

/**
 * OderemaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OderemaleRepository extends \Doctrine\ORM\EntityRepository
{
}
