<?php

namespace AdminBundle\Repository;

/**
 * SendemaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendemaleRepository extends \Doctrine\ORM\EntityRepository
{
}
