about_index:
    path:     /
    defaults: { _controller: "AdminBundle:About:index" }
    methods:  GET

about_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:About:edit" }
    methods:  [GET, POST]

#about_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "AdminBundle:About:delete" }
#    methods:  DELETE

#about_show:
#    path:     /{id}/show
#    defaults: { _controller: "AdminBundle:About:show" }
#    methods:  GET

#about_new:
#    path:     /new
#    defaults: { _controller: "AdminBundle:About:new" }
#    methods:  [GET, POST]