delivery_index:
    path:     /
    defaults: { _controller: "AdminBundle:Delivery:index" }
    methods:  GET

#delivery_show:
#    path:     /{id}/show
#    defaults: { _controller: "AdminBundle:Delivery:show" }
#    methods:  GET

#delivery_new:
#    path:     /new
#    defaults: { _controller: "AdminBundle:Delivery:new" }
#    methods:  [GET, POST]

delivery_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Delivery:edit" }
    methods:  [GET, POST]

#delivery_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "AdminBundle:Delivery:delete" }
#    methods:  DELETE
