payment_index:
    path:     /
    defaults: { _controller: "AdminBundle:Payment:index" }
    methods:  GET

#payment_show:
#    path:     /{id}/show
#    defaults: { _controller: "AdminBundle:Payment:show" }
#    methods:  GET

#payment_new:
#    path:     /new
#    defaults: { _controller: "AdminBundle:Payment:new" }
#    methods:  [GET, POST]

payment_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Payment:edit" }
    methods:  [GET, POST]

#payment_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "AdminBundle:Payment:delete" }
#    methods:  DELETE
